// Script para traducir los calendarios de Primefaces a español
PrimeFaces.locales['es'] = {
	closeText: 'Cerrar',
	prevText: 'Anterior',
	nextText: 'Siguiente',
	monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
	dayNamesShort: ['Dom','Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
	dayNamesMin: ['D','L','M','M','J','V','S'],
	weekHeader: 'Semana',
	firstDay: 1,
	isRTL: false,
	showMonthAfterYear: false,
	yearSuffix: '',
	timeOnlyTitle: 'Sólo hora',
	timeText: 'Tiempo',
	hourText: 'Hora',
	minuteText: 'Minuto',
	secondText: 'Segundo',
	currentText: 'Fecha actual',
	ampm: false,
	month: 'Mes',
	week: 'Semana',
	day: 'Día',
	allDayText : 'Todo el día'
};